// Banderas (flagcdn.com, CDN publico y gratuito) por pais.
// COUNTRY_CODES tambien se usa desde lib/tvSchedule.js para matchear equipos
// entre los nombres de football-data.org (ingles) y la grilla de TV (español).

const COUNTRY_CODES = {
  argentina: "ar",
  brazil: "br",
  brasil: "br",
  uruguay: "uy",
  colombia: "co",
  ecuador: "ec",
  paraguay: "py",
  chile: "cl",
  peru: "pe",
  bolivia: "bo",
  venezuela: "ve",
  mexico: "mx",
  "méxico": "mx",
  "usa": "us",
  "ee.uu.": "us",
  "united states": "us",
  canada: "ca",
  "canadá": "ca",
  "costa rica": "cr",
  panama: "pa",
  "panamá": "pa",
  honduras: "hn",
  jamaica: "jm",
  "el salvador": "sv",
  haiti: "ht",
  "haití": "ht",
  curacao: "cw",
  "curaçao": "cw",
  curazao: "cw",
  "trinidad and tobago": "tt",
  guatemala: "gt",
  france: "fr",
  francia: "fr",
  germany: "de",
  alemania: "de",
  spain: "es",
  "españa": "es",
  england: "gb-eng",
  inglaterra: "gb-eng",
  scotland: "gb-sct",
  escocia: "gb-sct",
  wales: "gb-wls",
  "northern ireland": "gb-nir",
  portugal: "pt",
  netherlands: "nl",
  "países bajos": "nl",
  holland: "nl",
  belgium: "be",
  "bélgica": "be",
  italy: "it",
  croatia: "hr",
  switzerland: "ch",
  suiza: "ch",
  poland: "pl",
  denmark: "dk",
  sweden: "se",
  suecia: "se",
  norway: "no",
  austria: "at",
  "czech republic": "cz",
  czechia: "cz",
  "rep. checa": "cz",
  slovakia: "sk",
  slovenia: "si",
  hungary: "hu",
  romania: "ro",
  serbia: "rs",
  ukraine: "ua",
  greece: "gr",
  turkey: "tr",
  "türkiye": "tr",
  "turquía": "tr",
  "republic of ireland": "ie",
  ireland: "ie",
  finland: "fi",
  iceland: "is",
  albania: "al",
  "bosnia and herzegovina": "ba",
  bosnia: "ba",
  "north macedonia": "mk",
  georgia: "ge",
  kosovo: "xk",
  morocco: "ma",
  marruecos: "ma",
  senegal: "sn",
  ghana: "gh",
  cameroon: "cm",
  tunisia: "tn",
  "túnez": "tn",
  algeria: "dz",
  argelia: "dz",
  nigeria: "ng",
  egypt: "eg",
  egipto: "eg",
  "south africa": "za",
  "sudáfrica": "za",
  "ivory coast": "ci",
  "côte d'ivoire": "ci",
  "cote d'ivoire": "ci",
  "costa de marfil": "ci",
  "cape verde": "cv",
  "cabo verde": "cv",
  "dr congo": "cd",
  "r.d. congo": "cd",
  mali: "ml",
  zambia: "zm",
  japan: "jp",
  "japón": "jp",
  "south korea": "kr",
  "korea republic": "kr",
  "corea del sur": "kr",
  "korea dpr": "kp",
  "saudi arabia": "sa",
  iran: "ir",
  "ir iran": "ir",
  qatar: "qa",
  australia: "au",
  "new zealand": "nz",
  "nueva zelanda": "nz",
  "united arab emirates": "ae",
  uae: "ae",
  iraq: "iq",
  jordan: "jo",
  jordania: "jo",
  uzbekistan: "uz",
  china: "cn",
  india: "in",
  vietnam: "vn",
  thailand: "th",
  indonesia: "id",
};

function normalize(name) {
  return (name || "").trim().toLowerCase();
}

// Codigo de pais (ISO2 o codigo flagcdn) a partir del nombre del equipo,
// en ingles o español. Devuelve null si no esta mapeado.
export function countryCode(teamName) {
  return COUNTRY_CODES[normalize(teamName)] || null;
}

// URL de la bandera del pais (CDN flagcdn.com, publico y gratuito).
export function getFlagUrl(teamName) {
  const code = countryCode(teamName);
  if (!code) return null;
  return `https://flagcdn.com/w80/${code}.png`;
}

export function isArgentina(name) {
  return normalize(name) === "argentina";
}
